Allow lowercase `type` on config entries
pulumi/pulumi-yaml pull request #275
Opened 2022-07-07 00:22 UTC by aq17

Addresses #201

2022-07-07 01:45 UTC, dixler requested changes
How are your changes already in the `main` branch?

2022-07-07 01:45 UTC, dixler commented on CHANGELOG_PENDING.md
> +  [#201](https://github.com/pulumi/pulumi-yaml/pull/201)
we use the pull request number rather than the issue number. I'm not sure why we do, but we do.

2022-07-07 15:55 UTC, aq17 commented
> How are your changes already in the `main` branch?

I have no idea 😟

2022-07-07 20:40 UTC, AaronFriel commented
🤞

2022-07-07 23:35 UTC, aq17 commented on pkg/pulumiyaml/config/config.go
> +		innerString := strings.TrimSuffix(strings.TrimPrefix(strings.TrimPrefix(s, "List<"), "list<"), ">")
Just realized that 😅

2022-07-07 23:38 UTC, aq17 commented on pkg/pulumiyaml/config/config.go
> +		innerString := strings.TrimSuffix(strings.TrimPrefix(strings.TrimPrefix(s, "List<"), "list<"), ">")
We lowercase s, and then only check/ trim `list<`

2022-07-08 00:39 UTC, AaronFriel approved these changes
LGTM, one nit: I'd change lines 94, 96, 98 to just have the lowercase versions as `s` will be lowercase.

2022-07-08 17:29 UTC, merged