Typecheck nested properties
pulumi/pulumi-yaml pull request #340
Opened 2022-09-21 23:25 UTC by aq17

Fixes #330

2022-09-23 19:43 UTC, iwahbe requested changes
I don't think that `typePropertyEntries` is the right place to put this. It serves to aggregate properties into a `schema.Type` and hand that off to `assertTypeAssignable`. I think the fix needs to live in `assertTypeAssignable`.

I'm pretty sure there is a bug in 

https://github.com/pulumi/pulumi-yaml/blob/60bfab81632daf5cb945e04b57412dc135fed4d8/pkg/pulumiyaml/analyser.go#L295-L321

`assertTypeAssignable` handles complications like `schema.Union`, which we need to account for.

2022-09-23 19:43 UTC, iwahbe commented on pkg/pulumiyaml/analyser.go
> +				prop := propMap[kvp.Key.Value]
This variable already exists as `typ`. It's bound during the if check.

2022-09-23 21:34 UTC, aq17 commented
> I don't think that `typePropertyEntries` is the right place to put this. It serves to aggregate properties into a `schema.Type` and hand that off to `assertTypeAssignable`. I think the fix needs to live in `isAssignable`.
> 
> I'm pretty sure there is a bug in
> 
> https://github.com/pulumi/pulumi-yaml/blob/60bfab81632daf5cb945e04b57412dc135fed4d8/pkg/pulumiyaml/analyser.go#L295-L321
> 
> `isAssignable` handles complications like `schema.Union`, which we need to account for.

I'm unsure how you get the subproperties (`from`) within just `isAssignable` though. If the`from` property is an object, we can get its subproperties and recursively call `isAssignable` (where `from` is now `to`), but what do we compare it to?

2022-09-24 01:20 UTC, iwahbe commented
`to` would also be an object, `isAssignable` just asserts that an object fits within another object.

2022-09-26 16:48 UTC, closed without merging