Do not error on duplicate config keys
pulumi/pulumi-yaml pull request #402
Opened 2022-11-07 18:28 UTC by aq17

Fixes #401

2022-11-07 19:06 UTC, AaronFriel requested changes

2022-11-08 21:44 UTC, AaronFriel commented on pkg/tests/example_transpile_test.go
> +			// assert.Len(t, diags, 0, "Should have neither warnings nor errors")
Can we change this to a loop to filter out diags containing `` "`configuration` field is deprecated" ``?

2022-11-08 22:05 UTC, AaronFriel approved these changes
LGTM!

2022-11-08 22:05 UTC, merged

2022-11-10 01:47 UTC, joeduffy commented
@aq17 @AaronFriel Glad to see a test in here, just wasn't immediately obvious it was protecting against the duplicate config key issue that led to the problem. Does it cover that? If yes, great! If not, should we be adding a new test?

2022-11-10 02:04 UTC, AaronFriel commented
It does & this PR removes the failure condition you found in #401. 

There are two follow ups here:
- Update our examples to remove the first warning on `up`. #404 
- Enhance `pulumi convert` to understand structured (typed) project level config, which will help us migrate our convert tests to use hierarchical config. #406 

```shell
❯ cd $(mktemp -d)

/tmp/tmp.qP70vtV5Ub 
❯ pulumi new kubernetes-gcp-yaml -y

Created project 'tmp.qP70vtV5Ub'

Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
Created stack 'dev'

Saved config

Your new project is ready to go! 

To perform an initial deployment, run `pulumi up`

/tmp/tmp.qP70vtV5Ub 
❯ pulumi preview
Previewing update (dev)

View Live: https://app.pulumi.com/friel/tmp.qP70vtV5Ub/dev/previews/edac5652-3dbc-4f18-bbfe-e7ca55a5c84f

     Type                           Name                Plan       Info
 +   pulumi:pulumi:Stack            tmp.qP70vtV5Ub-dev  create     1 warning; 1 message
 +   ├─ gcp:compute:Network         gke-network         create     
 +   ├─ gcp:compute:Subnetwork      gke-subnet          create     
 +   ├─ gcp:container:Cluster       gke-cluster         create     
 +   ├─ gcp:serviceAccount:Account  gke-nodepool-sa     create     
 +   └─ gcp:container:NodePool      gke-nodepool        create     


Diagnostics:
  pulumi:pulumi:Stack (tmp.qP70vtV5Ub-dev):
    Warning: Pulumi.yaml: root-level `configuration` field is deprecated; please use `config` instead.

    warning: unable to detect a global setting for GCP Project;
    Pulumi will rely on per-resource settings for this operation.
    Set the GCP Project by using:
        `pulumi config set gcp:project <project>`

Outputs:
    clusterId  : output<string>
    clusterName: "gke-cluster-2792fcd"
    kubeconfig : [secret]
    networkId  : output<string>
    networkName: "gke-network-f68e324"